### ISSUE TITLE
Bot can't change status, but users can

### ISSUE THREAD

**Issue by AdminRAT** [discordconsole-team/DiscordConsole#39]
I noticed that when logged in as a bot, you can't change it's status (online, idle, dnd, invisible), but you could with a user account. I've seen other bots have a change status command, so it would be nice to have the bot do that too.

**Comment by Mnpn03** [comment]
Hmm, it must have been disabled for a reason. I'll look into it.

**Comment by jD91mZM2** [comment]
This is supported in the rewrite IIRC

**Comment by Mnpn03** [comment]
This issue has been open for a while. Me and @jD91mZM2 discussed this a while ago, and we came to a conclusion.
DiscordGo uses the HTTP endpoint which does not allow this (hence why it's blocked). This request works with websockets though, because Discord decided that was a good idea. We have no idea if we can even get DiscordGo to work with websockets.
That's why I'll close this issue for now.
