### ISSUE TITLE
(Idea) New playing statuses

### ISSUE THREAD

**Issue by AdminRAT** [discordconsole-team/DiscordConsole#44]
I've seen some bots have different statuses other than "playing" (like "watching" or "listening"), and was wondering if this feature could be added

**Comment by Mnpn03** [comment]
I believe that this is only a Discord Rich Presence feature. Non-RPC statuses are the regular “playing” and “streaming”.

If DiscordGo allows this I do not know but it may be possible to make DiscordConsole into a Discord game, but I’m unsure of how that would work.

**Comment by AdminRAT** [comment]
I don't think it's the Rich Presence part when I tested it with a bot without it enabled...

**Comment by Mnpn03** [comment]
@jD91mZM2

**Comment by jD91mZM2** [comment]
Why are you tagging me? I left this project. The Discord API is changing too much, and the T.O.S. is too strict.

**Comment by Mnpn03** [comment]
^Can agree with the API and ToS but I was just asking for any input but alright

**Comment by jD91mZM2** [comment]
I have never heard of this feature, but if you want it, sure, feel free to knock yourself out ;)

**Comment by Mnpn03** [comment]
e024939 finally adds this. It will be in the next release, and usage will be in the release notes. The name of the command isn't final, so that's why I'm being cryptic about it :)

Apologies for taking this long to implement it, I found the related discordgo functions when browsing godoc yesterday.

Here are screenshots:
![image](https://user-images.githubusercontent.com/17569187/62859938-fe8ed780-bcfe-11e9-8971-fc809112bbea.png)
![image](https://user-images.githubusercontent.com/17569187/62859991-241be100-bcff-11e9-8f3a-834e38bedbbe.png)
![image](https://user-images.githubusercontent.com/17569187/62860068-562d4300-bcff-11e9-920a-b836cffcbc4b.png)

If this isn't the behaviour you requested, feel free to reopen this issue.
