### ISSUE TITLE
.autorun function broken

### ISSUE THREAD

**Issue by dmack6464** [discordconsole-team/DiscordConsole#46]
When I create an .autorun file and I try to log in with my token using it, it processes it with a \r at the end, and therefore throws an error.
It works fine if I don't have a newline at the end, so I'm thinking its something to do with how it handles files encoded by the Windows Notepad.
Oh, it does even weirder things if you try putting the token in quotes for some reason.

**Comment by Mnpn03** [comment]
DiscordConsole never accepts a token with quotes. You are correct though - Windows file endings (CRLF) don’t work. This is usually fine if you don’t make a new line, as you said, but it removed the functionality of running commands on startup. I do believe Windows 1809 comes with an updated Notepad where you can select LF line endings. Otherwise, try another program like Notepad++ or Sublime Text. They should allow you to also set the file endings.
